model:
  tensorflow:
    module: https://tfhub.dev/google/imagenet/inception_resnet_v2/classification/5
    classes: https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt
    target_size: (299, 299)